### ISSUE TITLE
上传报HASH计算错误

### ISSUE THREAD

**Issue by lovechang1986** [aoaostar/alidrive-uploader#48]
之前一直用着没什么问题，今天突然发现自动上传的程序出错了，查了好几遍弹出hash计算错误。
[38](https://github.com/Hidove/aliyundrive-uploader/issues/38)和[24](https://github.com/Hidove/aliyundrive-uploader/issues/24)都记录到了该错误。

为了确认问题，我检查了阿里云盘的refreash_token，发现变动了，于是我把变动的token更新到config.json中，不曾想再次运行的时候程序会自动修改config.json，不知道这种事什么情况。。。
![image](https://user-images.githubusercontent.com/8605164/156656563-c85f7956-563a-4cbb-ae0a-3a0157b80f80.png)

**Comment by aoaostar** [comment]
已解决
